In [30]:
#Part 1 – Implement Basic Data Structures using Numpy, Pandas

import numpy as np
l1=[101,22,15]
a1=np.array(l1)
print("list=",l1)
print("array=",a1)
print("type=",type(a1))
print("type=",type(l1))

list= [101, 22, 15]
array= [101  22  15]
type= <class 'numpy.ndarray'>
type= <class 'list'>


In [31]:
import numpy as np
arr1=(10,11,12)
arr2=(20,12,22)
mul=np.multiply(arr1,arr2)
print(mul)
div=np.divide(arr1,arr2)
print(div)
pow=np.power(arr1,arr2)
print(pow)

[200 132 264]
[0.5        0.91666667 0.54545455]
[7766279631452241920       3138428376721 5729018530666381312]


In [32]:
result= arr1 + arr2

# Create a textual output
output_text = f"Addition of Two Arrays:\narray1 + array2 = {result}"

# Print the result
print(output_text)

Addition of Two Arrays:
array1 + array2 = (10, 11, 12, 20, 12, 22)


In [33]:
print(np.sin(0))
print(np.cos(0))
print(np.log(20))
print(np.exp(2.23))

0.0
1.0
2.995732273553991
9.299866079483586
